# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0cbf75c7bb04c9ef20cdfe8cafdba72415310c0d4c8e0c0aca52fb121d3b2068d5614b593b07140c41879dabb45de1080d622b92656c4546d69b2e57219b4cc

test:
  secret_key_base: 922f848077c5525c531679fb34d07c0f8b7a7ff61bfcf85d5311c08c62dac46eb8207f030dc17fe5c10fb89ac1290fb5ce080127b474f51502b0b7500b9775eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
